Repository dnd-side-project/dnd-10th-8-android, pull requests merged in 2024-02, with the labels that each got.

#32 [Feature] 경조사 그룹 추가 BottomSheet
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/member/AddGroupUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
Labels: priority: medium, develop: feature, state: in review

#34 [Feat] 경조사비 메인 구현
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/history/HistoryInfo.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/history/GetHistoryGroupListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/history/GetHistoryInfoUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/ChipItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/ChipType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/GroupChipListComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/HistoryMainConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/HistoryMainEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/HistoryMainIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/HistoryMainModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/HistoryMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/HistoryMainState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/item/HistoryRelationItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/type/HistorySortedType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/type/HistoryViewType.kt
  presentation/src/main/res/drawable/ic_notification.xml
  presentation/src/main/res/drawable/ic_notification_on.xml
  presentation/src/main/res/drawable/ic_search.xml
Labels: priority: medium, develop: feature, state: in review

#33 [Setting] 캘린더 컴포넌트 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarColorProperties.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarConfig.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarDay.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarDayType.kt
Labels: priority: low, state: in review

#35 [Setting]: 금액 입력 텍스트 필드 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/expansion/NumberCommaTransformation.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/PriceChipComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingPriceField.kt
  presentation/src/main/res/drawable/ic_essential_field.xml
Labels: priority: low, state: in review

#36 [Feature] API 연결
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/AuthenticationApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/GroupApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/HeartApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/MemberApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/RelationApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/ScheduleApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/StatisticsApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/group/AddGroupReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/group/AddGroupRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/group/EditGroupReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/group/GetGroupListRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/AddHeartReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/AddHeartRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/AddUnrecordedHeartReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/AddUnrecordedHeartRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/EditHeartReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/GetHeartListRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/GetRelatedHeartListRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/member/EditProfileReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/member/GetProfileRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/relation/AddRelationReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/relation/AddRelationRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/relation/EditRelationReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/relation/GetRelationListRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/relation/GetRelationRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/AddScheduleReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/AddScheduleRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/EditScheduleReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/GetUnrecordedScheduleListRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/statistics/GetGroupStatisticsRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/statistics/GetMyStatisticsRes.kt
Labels: priority: high, develop: feature, state: in review

#38 [Feature] PreSigned 관련 API / Repository 연결
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/FileApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/file/GetPreSignedUrlRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/file/MockFileRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/file/RealFileRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/file/PreSignedUrl.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/FileRepository.kt
Labels: priority: high, develop: feature, state: in review

#39 [Feature] UseCase 연결
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/group/AddGroupUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/group/DeleteGroupUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/group/EditGroupUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/group/GetGroupListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/heart/AddHeartUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/heart/AddUnrecordedHeartUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/heart/DeleteHeartUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/heart/EditHeartUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/heart/GetHeartListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/heart/GetRelatedHeartListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/member/CheckNicknameUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/member/EditProfileUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/relation/AddRelationUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/relation/DeleteRelationUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/relation/EditRelationUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/relation/GetRelationListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/relation/GetRelationUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/AddScheduleUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/DeleteScheduleUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/EditScheduleUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/GetUnrecordedScheduleListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/statistics/GetGroupStatisticsUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/statistics/GetMyStatisticsUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/file/GetPreSignedUrlUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/file/UploadImageUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/legacy/GetGroupListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/legacy/GetHistoryGroupListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/legacy/GetHistoryInfoUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/member/AddGroupUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/relation/GetRelationUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainViewModel.kt
Labels: priority: high, develop: feature, state: in review

#41 [Setting] NotificationUtil
  app/src/main/kotlin/ac/dnd/bookkeeping/android/BookkeepingApplication.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/Constants.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/NotificationUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
Labels: priority: low, state: in review

#43 [Setting] DialogScreen isShowing 제거
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/ComposeUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/DialogScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainScreen.kt
Labels: priority: medium, develop: refactoring, state: in review

#42 [Feature] 마음 조회하기 Response Model 변경
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/FileApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/authentication/LoginRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/authentication/RegisterRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/AddHeartRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/AddUnrecordedHeartRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/GetHeartListRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/relation/AddRelationRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/AddScheduleRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/util/NetworkUtil.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/authentication/sociallogin/KakaoLoginRepositoryImpl.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/heart/MockHeartRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/heart/Heart.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/heart/RelatedHeart.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/relation/RelationDetail.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/relation/RelationSimple.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/schedule/UnrecordedSchedule.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/GroupChipListComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingPriceField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainScreen.kt
Labels: priority: medium, develop: feature, state: in review

#44 [Setting] Error Message 처리 고도화
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/base/BaseViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/base/ErrorEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/ComposeUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/HistoryMainEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/HistoryMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: priority: high, develop: refactoring, state: in review

#45 [Feature] 마음 등록 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/BottomSheetScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/ChipItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/GroupChipListComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/component/FieldSelectComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/component/FieldSubjectComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/PriceChipComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingPriceField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/HistoryMainViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/calendar/HistoryCalendarScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/type/HistoryRegistrationEventType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/type/HistoryRegistrationTagType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/type/HistoryRegistrationType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/RegistrationNavGraph.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainDestination.kt
Labels: priority: medium, develop: feature, state: in review

#47 [Feature] History 파일구조 변경
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/group/GroupWithRelationDetail.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/group/GroupWithRelationSimple.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/group/GetGroupHeartHistoryUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/group/GetGroupListWithRelationSimpleUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/GroupChipListComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryRegistrationEventType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryRegistrationTagType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryRegistrationType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistorySortedType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryViewType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/calendar/HistoryCalendarScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/get/GetRelationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/get/GetRelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/get/GetRelationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryRelationItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/item/HistoryDetailEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/item/HistoryDetailIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/item/HistoryDetailModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/item/HistoryDetailState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/item/HistoryDetailViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
Labels: priority: high, develop: refactoring, state: in review

#50 [Feature] History 구조 추가
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#48 [Feature]: 관계등록 ui 로직 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/component/FieldSubjectComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/confirm/ConfirmButton.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingPriceField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/add/AddRelationConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/add/AddRelationDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/add/AddRelationEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/add/AddRelationIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/add/AddRelationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/add/AddRelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/add/AddRelationState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/add/AddRelationViewModel.kt
  presentation/src/main/res/drawable/ic_camera.xml
  presentation/src/main/res/drawable/ic_chevron_left.xml
Labels: priority: medium, state: in review

#51 [Setting] 갤러리 ui & 붙이기
  app/src/main/AndroidManifest.xml
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/local/gallery/GalleryImageRepositoryImpl.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/local/gallery/GalleryPagingSource.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/gallery/GalleryRepositoryImpl.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/gallery/GalleryFolder.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/gallery/GalleryImage.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/GalleryImageRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/GalleryRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/gallery/GetFolderListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/gallery/GetPhotoListUseCase.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/GalleryIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/GalleryModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/GalleryScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/GalleryState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/GalleryViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/item/GalleryItemContent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeScreen.kt
Labels: priority: medium, state: in review

#53 [Setting] 카카오 피커 & 연동 구현
  app/build.gradle.kts
  data/build.gradle.kts
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/relation/KakaoFriendRepositoryImpl.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/relation/KakaoFriendInfo.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/KakaoFriendRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/relation/GetKakaoFriendInfoUseCase.kt
  gradle/libs.versions.toml
Labels: priority: medium, state: in review

#54 [Feature] Schedule 구조 추가
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/add/AddRelationConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/get/GetRelationConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/notification/ScheduleAddNotificationEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/notification/ScheduleAddNotificationIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/notification/ScheduleAddNotificationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/notification/ScheduleAddNotificationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/notification/ScheduleAddNotificationState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/notification/ScheduleAddNotificationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/repeat/ScheduleAddRepeatEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/repeat/ScheduleAddRepeatIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/repeat/ScheduleAddRepeatModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/repeat/ScheduleAddRepeatScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/repeat/ScheduleAddRepeatState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/repeat/ScheduleAddRepeatViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#55 [Feature] Statistics, MyPage 구조 추가
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/profile/MyPageProfileConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/profile/MyPageProfileDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/profile/MyPageProfileEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/profile/MyPageProfileIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/profile/MyPageProfileModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/profile/MyPageProfileScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/profile/MyPageProfileState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/profile/MyPageProfileViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/MyPageSettingConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/MyPageSettingDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/MyPageSettingEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/MyPageSettingIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/MyPageSettingModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/MyPageSettingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/MyPageSettingState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/MyPageSettingViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/StatisticsConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/StatisticsEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/StatisticsIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/StatisticsModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/StatisticsScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/StatisticsState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/StatisticsViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#57 [Feature] HistoryDetail 내역 보기 & 수정 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/expansion/Shadow.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/BottomSheetScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/component/FieldSelectComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingPriceField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryEventType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryTagType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/calendar/EventTypeScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
Labels: develop: feature, state: in review

#59 [Feature] 관계 정보 구현
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/relation/GetRelationRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/relation/MockRelationRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/relation/RealRelationRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/relation/RelationDetailWithUserInfo.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/RelationRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/relation/GetRelationUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationScreen.kt
Labels: priority: medium, state: in review

#60 [Feature] 성장 단계 레벨 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryDetailGrowthType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthScreen.kt
Labels: priority: medium, state: in review

#61 [Setting] month selector 구현
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarConfig.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarPicker.kt
Labels: priority: medium, state: in review

#63 [Feature] 경조사비 내역 상세 구현
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryDetailGrowthType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryViewSwipingType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/common/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthScreen.kt
  presentation/src/main/res/drawable/bc_history_lv_1.xml
  presentation/src/main/res/drawable/bc_history_lv_2.xml
  presentation/src/main/res/drawable/bc_history_lv_3.xml
  presentation/src/main/res/drawable/bc_history_lv_4.xml
  presentation/src/main/res/drawable/bc_history_lv_5.xml
  presentation/src/main/res/drawable/bc_history_lv_6.xml
  presentation/src/main/res/drawable/ic_info.xml
Labels: priority: medium, state: in review

#65 [Feature]: 경조사비 내역 상세 page 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/expansion/Text.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryDetailSortedType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailViewModel.kt
  presentation/src/main/res/drawable/board.xml
Labels: priority: medium, state: in review

#64 [Feature] 기록되지 않은 일정 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryEventType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedViewModel.kt
  presentation/src/main/res/drawable/ic_unrecorded_flower.xml
Labels: priority: medium, state: in review

#66 [Feature] 일정 추가하기 구현
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/ScheduleApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/AddScheduleReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/EditScheduleReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/schedule/MockScheduleRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/schedule/RealScheduleRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/ScheduleRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/AddScheduleUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarPicker.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/schedule/ScheduleAlarmType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/notification/ScheduleAddNotificationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/repeat/ScheduleAddRepeatScreen.kt
Labels: priority: medium, develop: feature, state: in review

#69 [Feature]: time picker 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/TimePicker.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/TimePickerType.kt
Labels: priority: medium, state: in review

#67 [Feature] 경조사비 재구현
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/legacy/GetHistoryGroupListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/legacy/GetHistoryInfoUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/GroupChipListComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryDetailGrowthType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/group/get/type/DefaultGroupType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryRelationItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/common/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
  presentation/src/main/res/drawable/bc_history_lv_1.xml
  presentation/src/main/res/drawable/bc_history_lv_2.xml
  presentation/src/main/res/drawable/bc_history_lv_3.xml
  presentation/src/main/res/drawable/bc_history_lv_4.xml
  presentation/src/main/res/drawable/bc_history_lv_5.xml
  presentation/src/main/res/drawable/bc_history_lv_6.xml
  presentation/src/main/res/drawable/ic_close_circle_gray.xml
  presentation/src/main/res/drawable/ic_group_acquaintance.xml
  presentation/src/main/res/drawable/ic_group_family.xml
  presentation/src/main/res/drawable/ic_group_friend.xml
  presentation/src/main/res/drawable/ic_group_normal.xml
  presentation/src/main/res/drawable/ic_group_rectal.xml
  presentation/src/main/res/drawable/ic_history_flower.xml
  presentation/src/main/res/drawable/ic_logo.xml
  presentation/src/main/res/drawable/ic_property_lv_1.xml
  presentation/src/main/res/drawable/ic_property_lv_2.xml
  presentation/src/main/res/drawable/ic_property_lv_3.xml
  presentation/src/main/res/drawable/ic_property_lv_4.xml
  presentation/src/main/res/drawable/ic_property_lv_5.xml
  presentation/src/main/res/drawable/ic_property_lv_6.xml
  presentation/src/main/res/drawable/ic_schedule.xml
  presentation/src/main/res/drawable/ic_star.xml
Labels: priority: medium, state: in review

#70 [Feature] Schedule Screen 구현
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/schedule/MockScheduleRepository.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryEventType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreenHeader.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreenItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
  presentation/src/main/res/drawable/ic_drop_down.xml
  presentation/src/main/res/drawable/ic_event_birthday.xml
  presentation/src/main/res/drawable/ic_event_childbirth.xml
  presentation/src/main/res/drawable/ic_event_etc.xml
  presentation/src/main/res/drawable/ic_event_first_birthday_party.xml
  presentation/src/main/res/drawable/ic_event_marriage.xml
  presentation/src/main/res/drawable/ic_event_opening_of_business.xml
Labels: priority: medium, develop: feature, state: in review

#71 [Feature]: 마음 등록하기 구체화
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingPriceField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/calendar/HistoryCalendarScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationViewModel.kt
Labels: priority: medium, state: in review

#72 [Feature] Edit Schedule 구현
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/EditScheduleUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#73 [Setting]: TextField 스타일 적용
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
Labels: priority: low, state: in review

#75 [Feature] Statistics User 구현
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/statistics/GetGroupStatisticsRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/statistics/MockStatisticsRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/statistics/RealStatisticsRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/statistics/GroupStatistics.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/StatisticsRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/statistics/GetGroupStatisticsUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/expansion/Text.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chart/stick/StickChart.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chart/stick/StickChartData.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/StatisticsMeScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/StatisticsMeViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/StatisticsUserIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/StatisticsUserModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/StatisticsUserScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/StatisticsUserViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/group/StatisticsUserGroupEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/group/StatisticsUserGroupIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/group/StatisticsUserGroupModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/group/StatisticsUserGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/group/StatisticsUserGroupState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/group/StatisticsUserGroupViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/type/UserGender.kt
Labels: priority: medium, develop: feature, state: in review

#76 [Feature]: 내역 정보 수정 구체화
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/component/FieldSelectComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/event/EventTypeScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditViewModel.kt
  presentation/src/main/res/drawable/ic_alert_triangle_gray.xml
Labels: priority: medium, state: in review

#77 [Feature] Statistics Me Event 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/StatisticsMeScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/StatisticsUserScreen.kt
  presentation/src/main/res/drawable/ic_add_chart.xml
Labels: priority: medium, develop: feature, state: in review

#78 [Feature] 알람 구현
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/alarm/AlarmReceiver.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/alarm/AlarmUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/alarm/NotificationUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/test/TestScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#79 [Feature] NotificationScreen 구현
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/schedule/MockScheduleRepository.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/StatisticsScreen.kt
  presentation/src/main/res/drawable/ic_alarm.xml
Labels: priority: medium, develop: feature, state: in review

#80 [Feature] 메인 컬러 및 아이콘 수정
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/theme/Color.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chart/pie/PieChart.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/PriceChipComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/main/MainBottomBarItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/event/EventTypeScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/item/GalleryItemContent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/StatisticsMeScreen.kt
  presentation/src/main/res/drawable/ic_history_selected.xml
  presentation/src/main/res/drawable/ic_history_unselected.xml
  presentation/src/main/res/drawable/ic_mypage_selected.xml
  presentation/src/main/res/drawable/ic_mypage_unselected.xml
  presentation/src/main/res/drawable/ic_schedule_selected.xml
  presentation/src/main/res/drawable/ic_schedule_unselected.xml
  presentation/src/main/res/drawable/ic_statistics_selected.xml
  presentation/src/main/res/drawable/ic_statistics_unselected.xml
Labels: priority: medium, develop: feature, develop: refactoring, state: in review

#81 [Feature] Statistics 화면 디자인 검수
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarPicker.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chart/stick/StickChart.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chart/stick/StickChartData.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/ChipItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/StatisticsScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/StatisticsMeScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/StatisticsUserScreen.kt
Labels: priority: medium, develop: feature, state: in review

#83 [Feature]: 이름 선택 구체화 & 디자인 검수
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/get/GetRelationScreen.kt
  presentation/src/main/res/drawable/ic_check_circle_gray.xml
Labels: priority: medium, develop: feature, state: in review

#82 [Feature]: 그룹 선택 구체화 & 디자인 검수
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/group/get/GetGroupIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/group/get/GetGroupViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/test/TestScreen.kt
Labels: priority: medium, develop: feature, state: in review

#85 [Feature] Schedule 화면 디자인 검수
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/GetScheduleListRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/GetScheduleRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/schedule/MockScheduleRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/schedule/Schedule.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/GetScheduleUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/TimePicker.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreenHeader.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreenItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#87 [Feature]: 관계 등록 구체화 & 디자인 검수
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/relation/KakaoFriendRepositoryImpl.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/relation/AddRelationWithUploadUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/GalleryScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/GalleryViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthConstant.kt
  presentation/src/main/res/drawable/ic_default_user_image.xml
  presentation/src/main/res/drawable/ic_gift_activate.xml
  presentation/src/main/res/drawable/ic_gift_disabled.xml
  presentation/src/main/res/drawable/ic_polygon.xml
Labels: priority: medium, develop: feature, state: in review

#86 [Feature] 로그인 시 Sentry User 정보 설정
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/member/GetProfileRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/member/MockMemberRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/member/Profile.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/LoginUseCase.kt
Labels: priority: low, develop: feature, state: in review

#88 [Feature] 마이페이지 구현
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/member/GetProfileRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/member/MockMemberRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/member/Profile.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#90 [Fix] 빌드 오류 해결
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/member/GetProfileRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/member/MockMemberRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/member/Profile.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageViewModel.kt
Labels: priority: high, develop: bug fix, develop: feature, state: in review

#91 [Feature]: 로그인 구체화 & 디자인 검수
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/authentication/LoginRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/authentication/MockAuthenticationRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/authentication/RealAuthenticationRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/legacy/Login.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingViewType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
  presentation/src/main/res/drawable/bc_onboarding_1.xml
  presentation/src/main/res/drawable/bc_onboarding_2.xml
  presentation/src/main/res/drawable/bc_onboarding_3.xml
  presentation/src/main/res/drawable/ic_board.xml
  presentation/src/main/res/drawable/ic_kakao_login_button.xml
  presentation/src/main/res/drawable/ic_login_logo.xml
Labels: priority: medium, develop: feature, state: in review

#92 [Feature]: History 구체화 & 디자인 검수
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageScreen.kt
Labels: priority: medium, develop: feature, state: in review

#89 [Setting]: Time Picker 오류 수정
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/alarm/AlarmUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/TimePicker.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreenItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
Labels: priority: medium, develop: feature, state: in review

#93 [Setting] Room DB 적용
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/local/database/BookKeepingDatabase.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/local/database/sample/SampleDao.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/local/database/sample/SampleEntity.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/local/di/LocalModule.kt
Labels: priority: low, state: in review

#96 [Setting] Base URL 적용
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/environment/BaseUrlProvider.kt
Labels: priority: low, develop: feature, state: in review

#95 [Setting] Firebase 적용
  .github/workflows/android.yml
  .gitignore
  app/build.gradle.kts
  app/src/main/kotlin/ac/dnd/mour/android/MourApplication.kt
  build.gradle.kts
  common/build.gradle.kts
  data/build.gradle.kts
  domain/build.gradle.kts
  domain/src/main/kotlin/ac/dnd/mour/android/domain/usecase/authentication/LoginUseCase.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
Labels: priority: low, state: in review

#97 [Fix] Firebase Plugin Fix
  app/build.gradle.kts
  build.gradle.kts
  data/build.gradle.kts
  domain/build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
Labels: priority: high, develop: bug fix, state: in review

#102 [System] Invalid Token 체크
  app/build.gradle.kts
  app/src/main/kotlin/ac/dnd/mour/android/MourApplication.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/authentication/MockAuthenticationRepository.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/authentication/RealAuthenticationRepository.kt
  domain/src/main/kotlin/ac/dnd/mour/android/domain/repository/AuthenticationRepository.kt
  gradle/libs.versions.toml
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/invalid/InvalidJwtTokenActivity.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/invalid/InvalidJwtTokenViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: develop: bug fix, priority: medium, develop: feature, state: in review

#101 [Feature] Notification Screen QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/notification/NotificationScreen.kt
Labels: priority: medium, develop: feature, state: in review

#100 [Feature] Statistics QA
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/feature/statistics/MockStatisticsRepository.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/chart/stick/StickChart.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/chip/ChipItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/segment/SegmentControl.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/model/history/HistoryEventType.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/me/StatisticsMeScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/user/StatisticsUserScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/user/group/StatisticsUserGroupScreen.kt
Labels: priority: medium, develop: feature, state: in review

#105 [Feature]: 마이페이지 수정 구현
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/model/mypage/ProfileModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageDestination.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileConstant.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileDestination.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileEvent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileIntent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileState.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#103 [System] TokenRepository, TokenApi 분리
  app/proguard-rules.pro
  app/src/main/kotlin/ac/dnd/mour/android/MourApplication.kt
  data/proguard-rules.pro
  data/src/main/kotlin/ac/dnd/mour/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/AuthenticationApi.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/TokenApi.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/di/KtorModule.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/authentication/MockAuthenticationRepository.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/authentication/RealAuthenticationRepository.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/authentication/token/MockTokenRepository.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/authentication/token/RealTokenRepository.kt
  domain/src/main/kotlin/ac/dnd/mour/android/domain/repository/AuthenticationRepository.kt
  domain/src/main/kotlin/ac/dnd/mour/android/domain/repository/TokenRepository.kt
  domain/src/main/kotlin/ac/dnd/mour/android/domain/usecase/authentication/UpdateJwtTokenUseCase.kt
Labels: priority: high, develop: bug fix, state: in review

#108 [Setting] 서버 연결
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/environment/BaseUrlProvider.kt
  presentation/src/main/AndroidManifest.xml
Labels: priority: high, develop: bug fix, develop: feature, state: in review

#107 [Feature] 디자인 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/theme/Typography.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/StatisticsScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/me/StatisticsMeScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventScreen.kt
Labels: priority: low, develop: feature, state: in review

#109 [Feature] 경조사비 메인 디자인 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/chip/ChipItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/res/drawable/ic_alarm_white.xml
  presentation/src/main/res/drawable/ic_chevron_right_gray.xml
  presentation/src/main/res/drawable/ic_close_circle_inner_gray.xml
  presentation/src/main/res/drawable/ic_close_rounded.xml
  presentation/src/main/res/drawable/ic_history_check.xml
Labels: priority: medium, develop: feature, state: in review

#110 [Feature]: 관계 & 카카오톡 등록 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/component/FieldSubjectComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationScreen.kt
  presentation/src/main/res/drawable/ic_history_edit.xml
Labels: priority: medium, develop: feature, state: in review

#111 [Feature]: 그룹 선택 & 마음 등록 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/PriceChipComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingPriceField.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
Labels: priority: medium, develop: feature, state: in review

#112 [Feature]: 내역상세 & 성장 레벨 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationScreen.kt
  presentation/src/main/res/drawable/ic_chevron_down_history.xml
  presentation/src/main/res/drawable/ic_property_lv_4.xml
  presentation/src/main/res/drawable/ic_property_lv_5.xml
Labels: priority: medium, develop: feature, state: in review

#113 [Feature] 지난 일정 기록 & 등록된 내역 수정 디자인 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/component/FieldSelectComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedPageScreen.kt
  presentation/src/main/res/drawable/ic_text_field_chevron_right.xml
Labels: priority: medium, develop: feature, state: in review

#115 [Feature] 카카오 로그인 수정 & 마이페이지 QA
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/authentication/sociallogin/KakaoLoginRepositoryImpl.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/DialogScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawScreen.kt
Labels: priority: medium, develop: feature, state: in review

#116 [Feature]: 히스토리 1차 & 2차 디자인 QA 적용
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
  presentation/src/main/res/drawable/ic_close_circle_white.xml
  presentation/src/main/res/drawable/ic_search_history.xml
Labels: priority: medium, develop: feature, state: in review

#117 [Feature] 기능 QA
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/FileApi.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/HeartApi.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/MemberApi.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/RelationApi.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/ScheduleApi.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/StatisticsApi.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/util/NetworkUtil.kt
  domain/src/main/kotlin/ac/dnd/mour/android/domain/usecase/authentication/IsRefreshTokenEmptyUseCase.kt
  domain/src/main/kotlin/ac/dnd/mour/android/domain/usecase/authentication/UpdateJwtTokenUseCase.kt
  domain/src/main/kotlin/ac/dnd/mour/android/domain/usecase/feature/group/GetGroupHeartHistoryUseCase.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/util/ComposeUtil.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/notification/NotificationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/add/ScheduleAddViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/splash/SplashViewModel.kt
Labels: develop: bug fix, priority: medium, develop: feature, state: in review

#119 [Feature] 에러 메세지 처리
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/environment/ErrorMessageMapper.kt
  data/src/main/res/values/errors.xml
Labels: priority: medium, develop: feature, state: in review

#120 [Feature]: 이름 선택 디자인 수정 & 내역 상세 디자인 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/get/GetRelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
Labels: priority: medium, develop: feature, state: in review

#122 [Feature] 디자인 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/UserDateTypingField.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/StatisticsScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/me/StatisticsMeScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/user/StatisticsUserScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/registration/main/RegistrationMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/registration/main/component/RegistraionUserDate.kt
  presentation/src/main/res/drawable/bc_onboarding_1.png
  presentation/src/main/res/drawable/bc_onboarding_1.xml
  presentation/src/main/res/drawable/bc_onboarding_2.png
  presentation/src/main/res/drawable/bc_onboarding_2.xml
  presentation/src/main/res/drawable/bc_onboarding_3.png
  presentation/src/main/res/drawable/bc_onboarding_3.xml
  presentation/src/main/res/drawable/ic_alarm_mini.xml
  presentation/src/main/res/drawable/ic_statstics_no_data.xml
Labels: priority: medium, develop: feature, state: in review

#123 [Feature]: 기능 로직 수정 & 오류 해결
  gradle/libs.versions.toml
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/UserDateTypingField.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryIntent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/login/main/LoginMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/registration/main/component/RegistraionUserDate.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/splash/SplashViewModel.kt
  presentation/src/main/res/drawable/bc_login.png
Labels: priority: high, develop: feature, state: in review
