Repository dnd-side-project/dnd-10th-8-android, pull requests merged in 2024-03, with the labels that each got.

#126 [Feature] MA00,MA04 디자인 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/chip/ChipItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingPriceField.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/model/relation/DefaultGroupType.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryRelationItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/ScheduleScreenItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventScreen.kt
  presentation/src/main/res/drawable/ic_person_relation.xml
  presentation/src/main/res/raw/history_main_flower.json
Labels: priority: medium, develop: feature, state: in review

#127 [Feature] MA02,MA03,MA03 2차 디자인 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/calendar/CalendarComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/chip/ChipItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingPriceField.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/ApplicationState.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/common/calendar/HistoryCalendarScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/get/GetRelationIntent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/get/GetRelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/get/GetRelationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
Labels: priority: medium, develop: feature, state: in review

#128 [Feature] MA01,MA03 기능 & 디자인 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/component/FieldSelectComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeConstant.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeDestination.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupIntent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationIntent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryRelationItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailItem.kt
Labels: priority: medium, develop: feature, state: in review

#129 [Fix] Refresh Token Fix
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/TokenApi.kt
Labels: priority: high, develop: bug fix, state: in review

#131 [Feature] LO00 디자인 & 기능 QA
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageIntent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileEvent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileIntent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/login/main/LoginMainScreen.kt
  presentation/src/main/res/drawable/ic_kakao_logo.xml
Labels: priority: medium, develop: feature, state: in review

#132 [Feature] ST00,CA00 디자인 QA, 기능 수정
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/chart/pie/PieChart.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/notification/NotificationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/ScheduleScreenItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/me/StatisticsMeScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/user/group/StatisticsUserGroupScreen.kt
  presentation/src/main/res/drawable/ic_alarm_gray.xml
  presentation/src/main/res/drawable/ic_chevron_right_schedule.xml
  presentation/src/main/res/drawable/ic_trash_schedule.xml
Labels: priority: medium, develop: feature, state: in review

#133 [Fix] S3 File Upload Method Fix
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/FileApi.kt
Labels: priority: high, develop: bug fix, state: in review

#134 [Fix] 오류 & 최종 디자인 수정
  data/build.gradle.kts
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/model/statistics/GetGroupStatisticsRes.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/feature/statistics/MockStatisticsRepository.kt
  domain/src/main/kotlin/ac/dnd/mour/android/domain/model/feature/statistics/GroupStatistics.kt
  presentation/build.gradle.kts
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/util/KakaoLoginUtil.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/calendar/CalendarComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/MainSystemUiState.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeDestination.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/ScheduleScreenHeader.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/ScheduleScreenItem.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/add/ScheduleAddConstant.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/add/ScheduleAddDestination.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/add/ScheduleAddEvent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/add/ScheduleAddViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/user/StatisticsUserScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/login/main/LoginMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/login/main/LoginMainViewModel.kt
  presentation/src/main/res/drawable/ic_event_birthday.xml
  presentation/src/main/res/drawable/ic_event_childbirth.xml
  presentation/src/main/res/drawable/ic_event_etc.xml
  presentation/src/main/res/drawable/ic_event_first_birthday_party.xml
  presentation/src/main/res/drawable/ic_event_marriage.xml
  presentation/src/main/res/drawable/ic_event_opening_of_business.xml
Labels: priority: medium, develop: feature, state: in review

#135 [Feature] 이벤트 로그 등록
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/util/logevent/LogEventUtil.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/add/AddGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/edit/EditGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/get/GetRelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/login/main/LoginMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/login/onboarding/LoginOnBoardingScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/registration/main/RegistrationMainDestination.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/registration/main/RegistrationMainScreen.kt
Labels: priority: medium, develop: feature, state: in review

#137 [feat] 버전
  gradle/libs.versions.toml
Labels: priority: medium, develop: feature, state: in review

#138 [Fix] S3 Content Type
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/FileApi.kt
Labels: priority: medium, state: in review

#139 [Feature] 기능 추가 & 디자인 QA
  data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/ScheduleApi.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/feature/schedule/MockScheduleRepository.kt
  data/src/main/kotlin/ac/dnd/mour/android/data/repository/feature/schedule/RealScheduleRepository.kt
  domain/src/main/kotlin/ac/dnd/mour/android/domain/repository/ScheduleRepository.kt
  domain/src/main/kotlin/ac/dnd/mour/android/domain/usecase/feature/schedule/HideScheduleUseCase.kt
  gradle/libs.versions.toml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/calendar/TimePicker.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/common/calendar/HistoryCalendarScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupEvent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/get/GetRelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryIntent.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryViewModel.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageScreen.kt
  presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
Labels: priority: medium, develop: feature, state: in review

#142 [Fix] KakaoTalk Proguard Rule Fix
  app/proguard-rules.pro
Labels: priority: high, state: in review
