Repository dnd-side-project/dnd-10th-8-android, pull requests merged in 2024-01, with the labels that each got.

#1 🛠[Setting] Compose 기본 세팅과 템플릿 제작
  app/build.gradle.kts
  common/build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/root/LoginRootConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/root/MainRootConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/root/RootEntryPoint.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/root/ScreenRootConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/state/ApplicationState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/state/ManageSystemUiState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/bottombar/BottomBarItem.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/bottombar/BottomBarScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/bottombar/BottomGraph.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/login/LoginScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/login/LoginViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/login/OnBoardScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainActivity.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/theme/Color.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/theme/Shape.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/theme/Theme.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/theme/Type.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/navigation/LoginNavGraph.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/navigation/MainNavGraph.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/splash/SplashScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/splash/SplashViewModel.kt
  presentation/src/main/res/drawable/bottom_sample.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/values/strings.xml
Labels: priority: high, state: in review

#2 [Chore] PR 템플릿 작성
  .github/pull_request_template.md
  CODEOWNERS
Labels: priority: low, state: in review

#4 [Feat] Custom SubView 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/BottomSheetScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/CustomSnackBarHost.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/DialogScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/SnackBarScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
Labels: priority: medium, state: in review

#7 [System] Assigner 등록
  .github/CODEOWNERS
  CODEOWNERS
Labels: priority: low, state: in progress

#5 [Feature] Splash Login Event 연결
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/IsLoginSucceedUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/bookkeeping/GetBookkeepingInformationUseCase.kt
  gradle/libs.versions.toml
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/coroutine/CoroutineUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/ApplicationState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashViewModel.kt
  presentation/src/main/res/drawable/ic_launcher.xml
Labels: priority: medium, develop: feature, state: in review

#6 [System] Error Handling 고도화
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/AuthenticationApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/BookkeepingApi.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/base/BaseActivity.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/base/BaseViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/ComposeUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/coroutine/CoroutineUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/ApplicationState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainActivity.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/bookkeeping/BookkeepingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/LoginNavGraph.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/LoginScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
Labels: priority: high, state: in review

#10 [System] DialogScreen 고도화
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/ComposeUtil.kt
  presentation/src/main/res/values/strings.xml
Labels: priority: high, develop: bug fix

#12 [Feature] LoginNavGraph & LoginMainDestination 만들기
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainSystemUiState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/LoginConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/LoginNavGraph.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/LoginScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/OnBoardScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#17 [Feature] Authorization 로직 구현
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/AuthenticationApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/di/KtorModule.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/authentication/GetAccessTokenRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/authentication/LoginReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/authentication/LoginRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/error/ErrorRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/util/NetworkUtil.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/authentication/MockAuthenticationRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/authentication/RealAuthenticationRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/authentication/JwtToken.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/authentication/Login.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/AuthenticationRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/LoginUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/LogoutUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/UpdateJwtTokenUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/WithdrawUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#11 [Refactoring] 의존성 정리
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/theme.xml
  build.gradle.kts
  common/build.gradle.kts
  common/src/main/kotlin/ac/dnd/bookkeeping/android/common/BundleUtil.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/RecyclerViewUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/TextViewUtil.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/ViewUtil.kt
  presentation/src/main/res/drawable/ic_launcher.xml
  presentation/src/main/res/values/attrs.xml
  presentation/src/main/res/values/styles.xml
  presentation/src/main/res/values/theme.xml
Labels: priority: low, develop: refactoring, state: in review

#13 [Feature] OnBoardingDestination 만들기
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/LoginNavGraph.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#14 [Feature] RegistrationNavGraph & RegistrationDestination 만들기
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/RegistrationConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/RegistrationNavGraph.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/RegistrationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingViewModel.kt
Labels: priority: medium, develop: feature, state: in review

#20 [Setting] BasicTextField Component 구현
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/CustomTextField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: priority: medium, state: in review

#19 [Feature] 카카오 SDK 붙이기
  .github/workflows/android.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/ac/dnd/bookkeeping/android/BookkeepingApplication.kt
  data/build.gradle.kts
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/sociallogin/KakaoLoginRepositoryImpl.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/sociallogin/UserModel.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/sociallogin/KakaoLoginRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/sociallogin/GetKakaoUserInfoUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/sociallogin/LoginKakaoUseCase.kt
  gradle/libs.versions.toml
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainActivity.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/kakao_login_sample/SampleScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/kakao_login_sample/SampleViewModel.kt
  settings.gradle.kts
Labels: priority: high, develop: feature, state: in review

#25 [Refactoring] Splash Screen Migration
  app/src/main/res/values/strings.xml
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: develop: refactoring, state: in review

#24 [System] 디자인시스템 적용
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/theme/Color.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/theme/Dimen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/theme/Shape.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/theme/Theme.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/theme/Type.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/theme/Typography.kt
Labels: priority: medium, state: in review

#26 [System] ConfirmButton 디자인시스템 적용
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/theme/Theme.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/BottomSheetScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/ConfirmButton.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/DialogScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/confirm/ConfirmButton.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/confirm/ConfirmButtonProperties.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/confirm/ConfirmButtonSize.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/confirm/ConfirmButtonType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
Labels: priority: high, state: in review

#27 [Feature] API 연결
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/AuthenticationApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/MemberApi.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/di/ApiModule.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/error/RegisterReq.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/error/RegisterRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/member/CheckNicknameRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/sample/SampleInformationRes.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/authentication/MockAuthenticationRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/authentication/RealAuthenticationRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/bookkeeping/MockBookkeepingRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/bookkeeping/RealBookkeepingRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/member/MockMemberRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/member/RealMemberRepository.kt
  data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/sociallogin/KakaoLoginRepositoryImpl.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/authentication/Register.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/bookkeeping/BookkeepingInformation.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/AuthenticationRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/BookkeepingRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/KakaoLoginRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/MemberRepository.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/LogoutUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/sociallogin/GetKakaoUserInfoUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/sociallogin/LoginKakaoUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/bookkeeping/GetBookkeepingInformationUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/member/CheckNicknameUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/bookkeeping/BookkeepingInformationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/login/KakaoUserInformationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingDestination.kt
Labels: priority: medium, develop: feature, state: in review

#29 [Feature] 경조사 이름 검색
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/event/Group.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/event/Relation.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/member/GetGroupListUseCase.kt
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/relation/GetRelationUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationState.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
  presentation/src/main/res/drawable/ic_person.xml
Labels: priority: medium, develop: feature, state: in review

#30 [Setting]: TextField 디자인 시스템 적용과 오류 수정
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingTextField.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingTextFieldType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
Labels: priority: low, state: in review

#31 [Feature] RegistrationScreen UI 로직 구현
  domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/RegistrationUseCase.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainConstant.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainDestination.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainErrorType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainEvent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainIntent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainScreen.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainViewModel.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/component/ErrorUserNamingComponent.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/component/RegistraionUserDate.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/type/RegistrationMainNamingErrorType.kt
  presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/type/UserGender.kt
  presentation/src/main/res/drawable/ic_check_circle.xml
  presentation/src/main/res/drawable/ic_close_circle.xml
  presentation/src/main/res/values/strings.xml
Labels: priority: medium, develop: feature, state: in review
